version: '3.1'
services:
  web:
    build: ./odoo
    depends_on:
      - db
    ports:
      - "5680:5680"
      - "8095:8069"
    volumes:
      - "./odoo/config:/etc/odoo"
      - "./odoo/addons:/mnt/extra-addons/addons"
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=odoo17
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5495:5432"
  client:
    build:
      context: ./client_app
    ports:
      - "8000:8000"
    depends_on:
      - web
volumes:
  odoo-web-data:
  odoo-db-data: